### ISSUE TITLE
[rms] unter C3.4.0

### ISSUE THREAD

**Issue by Anke** [srhinow/rms-c3#18]
Hallo!
Was für eine super Erweiterung! Probiere sie gerade zum ersten Mal aus, und sie scheint unter Contao 3.4.0 einigermaßen zu funktionieren, nachdem ich Zeile 84+85 in system/modules/rms/rmsVersions.php wie folgt geändert habe:

<code>require_once TL_ROOT . '/vendor/phpspec/php-diff/lib/Diff.php';</code>
<code>require_once TL_ROOT . '/vendor/phpspec/php-diff/lib/Diff/Renderer/Html/Contao.php';</code>

Und die Datei Contao.php aus einer älteren Contao-Version nach /vendor/phpspec/php-diff/lib/Diff/Renderer/Html/ kopiert habe.

Eine ungelöste Kleinigkeit allerdings noch: Wir haben keine E-Mail-Benachrichtigung über eine Änderung bekommen. Weder das E-Mail-Log noch das System-Logs zeigen (Fehler-)Meldungen.

Viele Grüße,
Anke

**Comment by srhinow** [comment]
Hi Anke,

ich habe mir Contao 3.4 noch gar nicht angesehen und was sich da alles geändert hat. Haben die Contao-Entwickler die Diff -Funktion soweit neu aufgedröselt das man jetzt zusätzliche Interpreter dort anlegen kann? Danke für den Lösungsansatz.

wegen der Email: Es wird nur eine Email versendet wenn 
1. in dem Bereich eine Email-Adresse hinterlegt wurde (z.B. für die Content-Elemente unter Artikel ist das die Root-Seite unter Seitenstruktur, dort unter rms muss eine ein Verwalter zugewiesen sein mit gültiger Emailadresse in seinen Einstellungen)
2. in dem jeweiligen Bereich wo Änderungen durchgeführt wurden, wird nicht nach jedem speichern eine Email gesendet, sondern erst wenn vorher in der checkbox "Änderungsbescheid senden" ein Haken gesetzt wurde.

Gruß Sven

**Comment by srhinow** [comment]
läuft aktuell bis 3.5.27
