### ISSUE TITLE
News: The table name must not be empty

### ISSUE THREAD

**Issue by dhe** [srhinow/rms-c3#22]
Hey,
vielen Dank für die Erweiterung 'rms', hervorragendes Feature.

Ich habe nur ein Problem in dem Bereich "News". Selbst wenn ich als Admin eine neue News erstellen will, bekomme ich immer den Fehler: The table name must not be empty.
![bildschirmfoto 2015-03-16 um 10 53 13](https://cloud.githubusercontent.com/assets/130322/6663836/ae834d22-cbca-11e4-8b15-134effd415ca.png)

Woran kann das liegen? alle anderen Bereich funktionieren tadellos.

**Comment by srhinow** [comment]
hbas gerade mal hier mit contao 3.2.14 und nen frischen pull von github getestet und bei mir kommt diese Meldung nicht. Wird denn in der Adresszeile bei dir der get-Paramter "table" übergeben? Hast du noch andere Erweiterungen im Newsbereich installiert die in dem Ablauf dazwischen funken könnten? Welche Contao-Version hast du im Einsatz?

**Comment by srhinow** [comment]
Kommt die Meldung erst nach dem speichern oder wird diese gleich angezeigt?

**Comment by dhe** [comment]
Hey,
also:
1.  Contao 3.4.0
2. keine andere News-Erweiterung
3. Fehler erscheint erst beim speichern
4. GET Parameter ist gesetzt.
![contao_rms](https://cloud.githubusercontent.com/assets/130322/6664740/9e38ea5a-cbd2-11e4-8583-8ff36b56e0b2.png)

**Comment by dhe** [comment]
Hab's glaub gefunden:
rmsDefaultCallbacks.php

Zeile 43: $strTable = (\Input::get("table")) ? \Input::get("table") : 'tl_'.$this->Input->get("do");

Dann geht's

**Comment by srhinow** [comment]
Danke für die Lösung.
Ich habe jetzt auch in allen anderen Callback-Methoden der Datei 'rmsDefaultCallbacks.php' die Klammern eingefügt.
