### ISSUE TITLE
Contao 3.3.6 - Speichern von Artikel führt zu Fehler "Table name must not be empty"

### ISSUE THREAD

**Issue by simonIhlenfeldt** [srhinow/rms-c3#23]
Das abspeichern eines Artikels funktioniert nicht und es wird der Fehler "Table name must not be empty" unter dem Feld "Änderungsbescheid senden" angezeigt.

Dieser Fehler wird deshalb ausgegeben, da im File rmsHelper.php in Zeile 280 kein ptable mitgegeben wird.
```php
$RmsSectionSettings = $this->getRmsSectionSettings($dc->id,	$strTable, $dc->activeRecord->ptable);
```
$strTable, $dc->activeRecord->ptable ist hier NULL.

Ich konnte das Problem beheben indem ich im Falle eines Artikels die ptable auf tl_page setze, wie auch an anderen Stellen im Code schon gesehen.

```php
$ptable = $dc->activeRecord->ptable;
if(!($ptable) && $strTable == 'tl_article') $ptable = 'tl_page';
$RmsSectionSettings = $this->getRmsSectionSettings($dc->id,	$strTable, $ptable);
```

**Comment by srhinow** [comment]
ist in der aktuellen Version an dieser Stelle mit $dc->parentTable gelöst worden.
